version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: blastburger-mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: devburger
    volumes:
      - mongodb_data:/data/db
    networks:
      - blastburger-network

  postgres:
    image: postgres:15
    container_name: blastburger-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: devburger
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - blastburger-network

volumes:
  mongodb_data:
  postgres_data:

networks:
  blastburger-network:
    driver: bridge